// TaskBounty adapter compatibility marker
import { makeOpportunity } from '../opportunity.js';
import { boundedFetch } from './network.js';

const BASE='https://www.task-bounty.com/api/v1';
function rewardOf(x={}){const n=Number(x.bounty_cents??x.reward_cents??x.amount_cents??x.bounty_amount??x.reward??x.amount??0);if(!Number.isFinite(n))return 0;return (x.bounty_cents!=null||x.reward_cents!=null||x.amount_cents!=null)?n/100:n;}
function rowsOf(j){if(Array.isArray(j))return j;if(!j||typeof j!=='object')return [];for(const v of [j.tasks,j.items,j.bounties,j.results,j.data]){const r=rowsOf(v);if(r.length)return r;}return [];}
export function parseTaskBountyTasks(rows=[]){return rows.map((x,i)=>{const reward=rewardOf(x),state=String(x.state??x.status??'open').toLowerCase(),id=x.id??x.task_id??x.slug??i,claims=Number(x.submission_count??x.claims??x.solvers??0);return makeOpportunity({id:'taskbounty-'+id,source:'taskbounty',url:x.github_issue_url||x.issue_url||x.url||'https://www.task-bounty.com/browse/'+id,title:x.title||x.name||'TaskBounty task #'+id,reward,currency:String(x.currency||x.reward_currency||'USD').toUpperCase(),status:/closed|completed|cancelled|expired|paid|claimed|awarded/.test(state)?'closed':'open',active_claims:claims,ai_policy:'allowed',payment_confidence:0.93,competition_score:Math.max(.08,1/(1+claims)),requires_manual_payment:false,claim_api_available:true,submit_api_available:true,estimated_minutes:Number(x.estimated_minutes||0)||undefined,raw:x});}).filter(x=>x.reward>0);}
export async function discoverTaskBounty({limit=25,fetchImpl=fetch,apiKey=process.env.TASKBOUNTY_API_KEY}={}){const url=BASE+'/tasks?limit='+Math.min(100,Math.max(1,limit*4));const headers={accept:'application/json','user-agent':'moneyhunter-preflight/0.7'};if(apiKey)headers.authorization='Bearer '+apiKey;const res=await boundedFetch(fetchImpl,url,{headers});if(!res.ok)throw new Error('TaskBounty HTTP '+res.status);const rows=rowsOf(await res.json());return parseTaskBountyTasks(rows).slice(0,limit);}
export { rewardOf as parseTaskBountyReward };
