import { makeOpportunity } from '../opportunity.js';
import { boundedFetch } from './network.js';

const BASE='https://www.task-bounty.com/api/v1';
function money(v){if(v==null)return 0;if(typeof v==='object')return money(v.amount_cents??v.bounty_cents??v.reward_cents??v.amount??v.value);const s=String(v).replace(/[$,\s]/g,'');const n=Number(s);return Number.isFinite(n)?n:0;}
function unwrap(x){return x?.task&&typeof x.task==='object'?x.task:x?.bounty&&typeof x.bounty==='object'&&('title' in x.bounty||'id' in x.bounty)?x.bounty:x;}
function rewardOf(x={}){const b=unwrap(x);const cents=b.bounty_cents??b.reward_cents??b.amount_cents;if(cents!=null)return money(cents)/100;return money(b.bounty_amount??b.reward??b.amount??b.payout??b.prize);}
function rowsOf(j){if(typeof j==='string'){try{return rowsOf(JSON.parse(j));}catch{return [];}}if(Array.isArray(j))return j;if(!j||typeof j!=='object')return [];for(const v of [j.bounties,j.tasks,j.items,j.results,j.data,j.payload]){const r=rowsOf(v);if(r.length)return r;}return [];}
export function parseTaskBountyTasks(rows=[]){return rows.map((raw,i)=>{const x=unwrap(raw),reward=rewardOf(x),state=String(x.state??x.status??x.lifecycle_state??'open').toLowerCase(),id=x.id??x.task_id??x.slug??i,claims=Number(x.submission_count??x.submissions_count??x.claims??x.solvers??0),funded=x.funded!==false&&x.is_funded!==false&&x.funding_status!=='unfunded';return makeOpportunity({id:'taskbounty-'+id,source:'taskbounty',url:x.github_issue_url||x.issue_url||x.url||'https://www.task-bounty.com/browse/'+id,title:x.title||x.name||x.short_summary||'TaskBounty task #'+id,reward,currency:String(x.currency||x.reward_currency||x.payout_currency||x.bounty?.currency||'USD').toUpperCase(),status:(!funded||/closed|completed|cancelled|expired|paid|claimed|awarded|withdrawn/.test(state))?'closed':'open',active_claims:claims,ai_policy:String(x.ai_policy||'allowed').toLowerCase(),payment_confidence:funded?.93:.45,competition_score:Math.max(.08,1/(1+claims)),requires_manual_payment:false,claim_api_available:true,submit_api_available:true,estimated_minutes:Number(x.estimated_minutes||x.estimated_time_minutes||0)||undefined,raw:raw});}).filter(x=>x.reward>0);}
export async function discoverTaskBounty({limit=25,fetchImpl=fetch}={}){const params=new URLSearchParams({limit:String(Math.min(100,Math.max(1,limit*2)))});const url=BASE+'/bounties.json?'+params;const headers={accept:'application/json','user-agent':'moneyhunter-preflight/1.2'};const res=await boundedFetch(fetchImpl,url,{headers});if(!res.ok)throw new Error('TaskBounty HTTP '+res.status);const payload=await res.json();return parseTaskBountyTasks(rowsOf(payload)).slice(0,limit);}
export { rewardOf as parseTaskBountyReward };
