import { McpServer } from '@modelcontextprotocol/server';
import { serveStdio } from '@modelcontextprotocol/server/stdio';
import * as z from 'zod/v4';
import { analyzeIssueUrl } from './analyze.js';
import { runRadar } from './radar.js';
import { revenueChannels, buildRevenuePortfolio } from './channels.js';
import { PRICING } from './product.js';
serveStdio(()=>{const server=new McpServer({name:'moneyhunter-preflight',version:'0.5.1'});
server.registerTool('preflight_github_bounty',{title:'Preflight a GitHub bounty',description:'Analyze a public GitHub bounty/paid issue before an AI agent spends compute.',inputSchema:z.object({issue_url:z.string().url()})},async({issue_url})=>({content:[{type:'text',text:JSON.stringify(await analyzeIssueUrl(issue_url),null,2)}]}));
server.registerTool('find_paid_opportunities',{title:'Find paid AI-friendly opportunities',description:'Run the multi-source zero-LLM opportunity radar.',inputSchema:z.object({min_reward:z.number().min(0).default(5),limit:z.number().int().min(1).max(100).default(25)})},async({min_reward,limit})=>({content:[{type:'text',text:JSON.stringify(await runRadar({minReward:min_reward,limit}),null,2)}]}));
server.registerTool('revenue_channels',{title:'Revenue channel portfolio',description:'Return integrated and watched revenue channels plus human-action gates.',inputSchema:z.object({})},async()=>({content:[{type:'text',text:JSON.stringify({channels:revenueChannels(),portfolio:buildRevenuePortfolio()},null,2)}]}));
server.registerTool('check_payment_reliability',{title:'Check bounty payment reliability',description:'Return payment/funding signals and hard-stop warnings.',inputSchema:z.object({issue_url:z.string().url()})},async({issue_url})=>{const r=await analyzeIssueUrl(issue_url);return{content:[{type:'text',text:JSON.stringify({source:r.source,reward:r.reward,payment:r.payment,recommendation:r.recommendation,red_flags:r.red_flags},null,2)}]};});
server.registerTool('moneyhunter_pricing',{title:'MoneyHunter API pricing',description:'Return current pay-per-call prices.',inputSchema:z.object({})},async()=>({content:[{type:'text',text:JSON.stringify(PRICING,null,2)}]}));
console.error('moneyhunter-preflight MCP server running on stdio');return server;});