export const PRICING={currency:'USDC',settlement_target:'x402',network:'Base mainnet',network_id:'eip155:8453',paid_gateway:'https://moneyhunter-x402-gateway.onrender.com',tools:{bounty_preflight:{price_usd:.05,method:'POST',path:'/v1/preflight'},opportunity_radar:{price_usd:.10,method:'GET',path:'/v1/radar'},payment_reliability:{price_usd:.03,method:'POST',path:'/v1/payment-reliability'}}};
export const PUBLIC_MANIFEST={name:'MoneyHunter',version:'0.5.2',description:'Adaptive multi-source revenue intelligence for AI agents.',free_origin:'https://moneyhunter-preflight.onrender.com',paid_gateway:PRICING.paid_gateway,payments:{protocol:'x402 v2',network:PRICING.network,network_id:PRICING.network_id,currency:'USDC',status:'live'},features:['github_preflight','payment_reliability','adaptive_multi_source_radar','profit_router','strategy_self_improvement','multi_channel_revenue_portfolio','frantic_adapter','github_paid_issue_adapter','algora_adapter','opire_adapter','superteam_watch','shipradar_watch','agent_bounties_watch','direct_hire_channel','reusable_assets_channel','mcp_stdio','x402_mainnet','agent_discovery'],endpoints:{free_health:'https://moneyhunter-preflight.onrender.com/health',paid_health:'https://moneyhunter-x402-gateway.onrender.com/health',paid_preflight:'https://moneyhunter-x402-gateway.onrender.com/v1/preflight',paid_payment_reliability:'https://moneyhunter-x402-gateway.onrender.com/v1/payment-reliability',paid_radar:'https://moneyhunter-x402-gateway.onrender.com/v1/radar',channels:'https://moneyhunter-preflight.onrender.com/v1/channels',offers:'https://moneyhunter-preflight.onrender.com/v1/offers',pricing:'https://moneyhunter-preflight.onrender.com/v1/pricing',openapi:'https://moneyhunter-preflight.onrender.com/openapi.json',llms:'https://moneyhunter-preflight.onrender.com/llms.txt'},pricing:PRICING,disclaimer:'Scores are triage heuristics. They do not guarantee acceptance, payment, or legal/platform eligibility.'};
export const LLMS_TEXT=`# MoneyHunter
Protocol: x402 v2
Adaptive multi-source revenue intelligence and multi-channel revenue portfolio for AI agents.
Free discovery: https://moneyhunter-preflight.onrender.com
Paid x402 gateway: https://moneyhunter-x402-gateway.onrender.com
Base mainnet eip155:8453 / USDC

Paid tools:
POST /v1/preflight — $0.05 USDC
POST /v1/payment-reliability — $0.03 USDC
GET /v1/radar — $0.10 USDC

Free machine-readable portfolio:
GET /v1/channels — integrated bounty sources plus watched external channels and revenue lanes.
GET /v1/offers — machine-readable direct-hire services and reusable developer assets.

Radar ranks by expected USD/hour, payment reliability, AI fit, competition and source reliability, then builds a diversified execution portfolio. Scores are heuristics, not guarantees.
`;
export const OPENAPI={openapi:'3.1.0',info:{title:'MoneyHunter API',version:'0.5.1',description:'Adaptive multi-source paid-opportunity discovery and multi-channel revenue portfolio with x402 USDC payment on Base.'},servers:[{url:'https://moneyhunter-x402-gateway.onrender.com',description:'Production x402 gateway — Base mainnet USDC'},{url:'https://moneyhunter-preflight.onrender.com',description:'Free discovery/origin service'}],paths:{'/health':{get:{summary:'Health check',responses:{'200':{description:'Healthy'}}}},'/v1/pricing':{get:{summary:'Current pricing',responses:{'200':{description:'Pricing manifest'}}}},'/v1/channels':{get:{summary:'Revenue channel portfolio and human-action policy',responses:{'200':{description:'Channel portfolio'}}}},'/v1/radar':{get:{summary:'Rank live paid opportunities and build a diversified execution portfolio',parameters:[{name:'min_reward',in:'query',schema:{type:'number',default:5}},{name:'limit',in:'query',schema:{type:'integer',default:25,maximum:100}},{name:'sources',in:'query',schema:{type:'string',default:'frantic,github,algora,opire'}}],responses:{'200':{description:'Ranked opportunities plus strategy plan'},'402':{description:'Payment required'}}}},'/v1/preflight':{post:{summary:'Preflight one public GitHub bounty',responses:{'200':{description:'Preflight report'},'402':{description:'Payment required'},'422':{description:'Invalid or unsupported issue'}}}},'/v1/payment-reliability':{post:{summary:'Check payment/funding credibility',responses:{'200':{description:'Payment reliability report'},'402':{description:'Payment required'}}}}}};